version: '3.8'
services:
  web:
    # Run with the same uid and gid as the host suer
    user: "${DM_UID}:${DM_GID}"
    build:
      dockerfile: ./php/Dockerfile
      args:
        DM_UID: "${DM_UID}"
        DM_GID: "${DM_GID}"
    volumes:
      - .:/var/www/html
    ports:
      - "5000:80"
  mysql:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pxmboard
      MYSQL_USER: pxmboard
      MYSQL_PASSWORD: password
    volumes:
      - mariadb:/var/lib/mysql
      - ./install/sql/pxmboard-mysql.sql:/docker-entrypoint-initdb.d/pxmboard-mysql.sql
    ports:
      - "3306:3306"
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: pxmboard
      POSTGRES_USER: pxmboard
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./install/sql/pxmboard-postgres.sql:/docker-entrypoint-initdb.d/pxmobard-postgres.sql
    ports:
      - "5432:5434"
volumes:
  mariadb:
  postgres:
